version: '3'

services:

  demo-db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=monitoring_platform
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST_AUTH_METHOD=trust
    ports:
      - 3307:3306
    container_name: demo-db

  demo-be:
    image: be
    restart: always
    ports:
      - "8080:8080"
    environment:
      #- DB_IP=172.22.0.2
      - DB_IP=demo-db
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DBNAME=monitoring_platform
